### ISSUE TITLE
PA Review: Project management

### ISSUE THREAD

**Issue by afarahmand** [afarahmand/kicks#3]
- [x] Backend: DB, model, controller, views
- [x]  Redux Loop: ajax, actions, reducer
- [x]  Presentational components
- [x]  Project creation
- [x]  Project show page
- [x]  Styling
- [x]  Smooth, bug-free navigation
- [x]  Adequate and appropriate seeds

**Comment by afarahmand** [comment]
I think this feature is ready for review.  There is one minor but important issue remaining: when a user clicks on the button to create a project from the new project page, the page does not transition for redirect even though the project does get created.

**Comment by AAlfarho** [comment]
The bulk of this site is in the projects, this MVP is not yet complete, we are missing a couple of important features before we can lock this MVP down.

## Functionality
- [ ] Validate for projects title, description and/or short-blurb to be a minimum length.
- [ ] Add validation so we cant add a project with a date in the past.
- [ ] The show project page, does not really show the days left, only the date time is displayed.
- [ ] Let's get rid of the warnings on the _create project_ page, `Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.` and `The specified value "1518129493649" does not conform to the required format, "yyyy-MM-dd".` when submitting a form.
- [ ] Update and delete a project. Apologies for the messy project dummies, could not delete the projects, we might need to clean them up from the backend until the delete functionality is implemented.
- [ ] As mentioned, we should redirect to the project after successful creation.

## Style
- [ ] Let's add some padding to the `short-blurb` textarea.
- [ ] The `li's` rendering the errors are governed by the `.project-form-container li` giving them a blue-ish background, lets set a different style for this errors, removing padding and background should be fine, for errors only.

Assign this issue back to me once the latest updates addressing the above issues are pushed to the live version of the app.

**Comment by afarahmand** [comment]
Good Evening Andres,

   All of the remaining issues identified above have been resolved.

(1) The project model has been modified to validate the length of all of the identified fields for a minimum length appropriate to that field.

(2) We have added a new gem that handles date validation.  It works seamlessly.

(3) The show page now shows the number of days left.  The utils folder now includes a date_util file that includes a number of helped methods for formatting dates.  I would also like to note that the home page also now dynamically shows today's date.

(4) We no longer use the selected attribute for one of our options on select html tags.  I think I used value for one select and defaultValue for others.  In the end, the warnings are gone.  Also, the date utils have helped us get around the date format warnings.

(5) I added update and delete buttons to the show page.  The buttons only display when currentUser.id matches project.user_id.  Additionally, in App.jsx, the route for edit (/projects/:projectId/edit) is set as a ProtectedRoute .  Unfortunately, this only forces "a user" to be logged to access the edit page thereby allowing any user to directly go and edit any project by typing in the correct url.  Therefore, I went ahead and perform a comparison in the project form that will redirect a user who is logged in but who is not the creator of that particular project.

(6) We now redirect to the show page upon project creation.

(7) Padding added

(8) The error styling has been corrected.

**Comment by AAlfarho** [comment]
Good job, the validation of the project data is well handled. Great attention to detail, like not being to update the date of your project, and validating and protecting against this. 

With the latest updates, the MVP is complete.
Kudos!

On a side note, I'm not familiar with the date_valitor gem, however, for our case, I think we could have used the Time class to create our own custom validation.
```ruby
[3] pry(main)> Time.new.tomorrow < Time.new.yesterday
=> false
[4] pry(main)> Time.new.tomorrow > Time.new.yesterday
=> true
```
